INSERT INTO USER (ID,NAME,BIRTH_DATE) VALUES (1,'Todd',sysdate());
INSERT INTO USER (ID,NAME,BIRTH_DATE) VALUES (2,'Dave',sysdate());
INSERT INTO USER (ID,NAME,BIRTH_DATE) VALUES (3,'Shelly',sysdate());
INSERT INTO USER (ID,NAME,BIRTH_DATE) VALUES (4,'Mike',sysdate());

INSERT INTO POST (ID,USER_ID,MESSAGE)  VALUES (1,1,'Post Message 1');
INSERT INTO POST (ID,USER_ID,MESSAGE)  VALUES (2,1,'Post Message 2 for 1');
INSERT INTO POST (ID,USER_ID,MESSAGE)  VALUES (3,1,'Post Message 3 for 1');
INSERT INTO POST (ID,USER_ID,MESSAGE)  VALUES (4,2,'Post Message 2');
INSERT INTO POST (ID,USER_ID,MESSAGE)  VALUES (5,3,'Post Message 1');
INSERT INTO POST (ID,USER_ID,MESSAGE)  VALUES (6,1,'Post Message 1');
INSERT INTO POST (ID,USER_ID,MESSAGE)  VALUES (7,4,'Post Message 1');
INSERT INTO POST (ID,USER_ID,MESSAGE)  VALUES (8,2,'Post Message 1');